repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: detect-telegram-tokens
        name: "detect-telegram-tokens"
        entry: python3 hooks/detect_telegram_tokens.py
        language: python
