#!/bin/bash

# CMSysBot: {
# "root": "True",
# "source": "bridge"
# }

dpkg -s arp-scan &>/dev/null

if [[ $? != 0 ]]; then
  sudo apt-get -y install arp-scan &>/dev/null
fi

ARP_SCAN_OUTPUT=$(sudo arp-scan -l | cut -f 1,2 | tail -n +3 | head -n -3)
echo "$ARP_SCAN_OUTPUT"
