#!/bin/bash

# CMSysBot: {
#   "root": "True",
#   "source" : "remote",
#   "arguments": ["Please enter a software name to check: "]
# }

IS_INSTALLED=`dpkg --get-selections | grep $1`

if [ -z "$IS_INSTALLED" ]
then
      echo "Not installed"
else
      echo "Installed"
fi
