#!/bin/bash

# CMSysBot: {
#   "root": "True",
#   "source" : "remote",
#   "arguments": ["Please enter a software name to check: "]
# }

# Check if software is installed
dpkg -s $1 &>/dev/null

if [[ $? != 0 ]]; then
  printf "Not installed."
else
  printf "Installed."
fi
