#!/bin/bash

#    CMSysBot: "$TARGET_IP", "$USERNAME", "$PASSWORD", "Script", "HUehue"

# Variables = arguments
IP=$1
USER=$2
PASS=$3
SCRIPT=$4

# Copy script to target IP:/path/
sshpass -p $PASS scp /tmp/$SCRIPT $USER@$IP:/tmp/

# Execute script in target IP as root
sleep 5
sshpass -p $PASS ssh $USER@$IP "echo $PASS | sudo -S /tmp/$SCRIPT"
