#!/bin/bash

# CMSysBot: {
# "root": "False",
# "source": "bridge",
# "arguments": ["$MACS_LIST"]
# }

MACS_LIST="$@"

if [ -z "$MACS_LIST" ]; then
  printf "You didnt specified any mac address."
else
  wakeonlan $MACS_LIST
fi

